### ISSUE TITLE
Notifications "You exceeded your current quota, please check your plan and billing details." instead of proper responds.

### ISSUE THREAD

**Issue by EugeneTarasenko** [chrislemke/ChatFred#112]
I had a look at the [troubleshooting section](https://github.com/chrislemke/ChatFred#troubleshooting-%EF%B8%8F)
- [ X] Yes
- [ ] No

I keep getting the notification "You exceeded your current quota, please check your plan and billing details." as a respond. I've just started using chatGPT. I created an account only 10 minutes ago. It's free. ChatGPT works absolutely fine in browser. I created an API key to use it with ChatFred.  I've made only few requests and there is no way my quota could have been exceeded already.
Am I doing something wrong?
I would appreciate any help.

**To Reproduce**
1. Launch Alfred Prompt
2. type `cf <any question>`
3. get a respond `"You exceeded your current quota, please check your plan and billing details."`  

**Screenshots**
![Screenshot 2023-09-14 at 06 22 53](https://github.com/chrislemke/ChatFred/assets/87163666/190dc38d-a608-47a4-af15-c000f30724bc)

**Relevant information from the `ChatFred_Error.log` file**
```
---
Date/Time: 2023-09-14 06:24:24.663460
model: gpt-3.5-turbo
workflow_version: 1.5.3
error_message: You exceeded your current quota, please check your plan and billing details.
user_prompt: hello
temperature: 0.0
max_tokens: None
top_p: 1
frequency_penalty: 0.0
presence_penalty: 0.0
---
Date/Time: 2023-09-14 06:27:50.589864
model: gpt-3.5-turbo
workflow_version: 1.5.3
error_message: You exceeded your current quota, please check your plan and billing details.
user_prompt: tell me a joke
temperature: 0.0
max_tokens: None
top_p: 1
frequency_penalty: 0.0
presence_penalty: 0.0

```

**Comment by chrislemke** [comment]
Hey @EugeneTarasenko!
Whenever you get such an error message you can answer with e.g. `wtf` to receive the original OpenAI error message. It seems to be what it says:  

> You exceeded your current quota, please check your plan and billing details.

Here is a link with some additional information:
https://help.openai.com/en/articles/6891831-error-code-429-you-exceeded-your-current-quota-please-check-your-plan-and-billing-details

Hope this helped. Please reach out if you need further assistance.

**Comment by chrislemke** [comment]
Hey @EugeneTarasenko!

Any news concerning this issue or shall I close it?

**Comment by EugeneTarasenko** [comment]
I haven’t fixed it, but you can closed it.
