### ISSUE TITLE
Gallery version is outdated

### ISSUE THREAD

**Issue by luckman212** [chrislemke/ChatFred#118]
Love this workflow! ✨ 

Not a bug, just a comment that when I use Alfred's _"Check for Workflow Updates"_ feature, it reports that there's an update to ChatFred. But, it tries to "update" my current version **1.6.1** _down_ to 1.5.3.

This is more of a problem with the way the Alfred Gallery function works (in my opinion) but, as we have little control over that, it would be good to at least keep parity between [the version published there][1] and the [latest GitHub release][2].

<img width="437" alt="image" src="https://github.com/chrislemke/ChatFred/assets/1992842/78b11e48-8f03-44cc-a8bf-6702e22b77bc">

[1]: https://alfred.app/workflows/chrislemke/chatfred/
[2]: https://github.com/chrislemke/ChatFred/releases/tag/v1.6.1

**Comment by chrislemke** [comment]
Hey @luckman212!

That's correct! We are still working on a suitable gallery version since the acceptance criteria have not been met yet. Thanks for pointing it out!
