### ISSUE TITLE
Network error

### ISSUE THREAD

**Issue by kraonn** [chrislemke/ChatFred#12]
I've installed the workflow from the Alfred gallery and I'm getting an error message about something being "fishy" about my network connection when I try to use any of the 3 options. I see this is invoking Python scripts and my next troubleshooting step would be to try to run those python scripts directly, but I am not able to locate them. Help?

**Comment by chrislemke** [comment]
Hey @kraonn!
Thanks for your message. I will look into it. Would be great if you check the script - as you mentioned. If you debug you can get the error message from OpenAI. That would help a lot.

**Comment by kraonn** [comment]
Thanks for responding. I would like to just run the script in terminal, but I cannot find where it's installed? What's the full path for the scripts that are a part of this workflow? I'm not an Alfred workflow expert so I don't know where those live.

**Comment by chrislemke** [comment]
You can find the scripts in the `src` folder. With a right-click on the Workflow, you can open it in the finder. If you are using ChatFred you are looking for the `text_chat.py` script.

**Comment by chrislemke** [comment]
Hey @kraonn! 
I could not reproduce your issue. Were you able to find out anything?

**Comment by cindy9923** [comment]
I also encountered the same problem as @kraonn , I ran `user.workflow.F136CC17-C621-4B37-8CBF-70F810CC658D % python3 src/text_chat.py $1` in the terminal to return the result 
```
Traceback (most recent call last):
  File "/Users/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.F136CC17-C621-4B37-8CBF-70F810CC658D/src/text_chat.py", line 8, in <module>
    from error_handling import env_value_error_if_needed, exception_response
  File "/Users/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.F136CC17-C621-4B37-8CBF-70F810CC658D/src/error_handling.py", line 9, in <module>
    import openai
  File "/Users/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.F136CC17-C621-4B37-8CBF-70F810CC658D/src/libs/openai/__init__.py", line 9, in <module>
    from openai.api_resources import (
  File "/Users/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.F136CC17-C621-4B37-8CBF-70F810CC658D/src/libs/openai/api_resources/__init__.py", line 7, in <module>
    from openai.api_resources.embedding import Embedding  # noqa: F401
  File "/Users/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.F136CC17-C621-4B37-8CBF-70F810CC658D/src/libs/openai/api_resources/embedding.py", line 7, in <module>
    from openai.datalib import numpy as np, assert_has_numpy
  File "/Users/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.F136CC17-C621-4B37-8CBF-70F810CC658D/src/libs/openai/datalib.py", line 22, in <module>
    import pandas
  File "/opt/anaconda3/lib/python3.9/site-packages/pandas/__init__.py", line 22, in <module>
    from pandas.compat import is_numpy_dev as _is_numpy_dev  # pyright: ignore # noqa:F401
  File "/opt/anaconda3/lib/python3.9/site-packages/pandas/compat/__init__.py", line 17, in <module>
    from pandas._typing import F
  File "/opt/anaconda3/lib/python3.9/site-packages/pandas/_typing.py", line 79, in <module>
    ArrayLike = Union["ExtensionArray", np.ndarray]
AttributeError: module 'numpy' has no attribute 'ndarray'
```

**Comment by kraonn** [comment]
Still an issue for me. I installed openai but the installation command above to install the datalib dependencies fails for me, it says openai[datalib] is not found. Probably something dumb, I'm a novice with installing Python packages.

**Comment by chrislemke** [comment]
Could you check if you have Pandas and NumPy installed and if so which version?

**Comment by kraonn** [comment]
Neither was, I manually installed both. 

Now it works fine from the terminal if I invoke the script there, but the ChatFred workflow still is returning the same "fishy internet connection" error message.

**Comment by chrislemke** [comment]
If you are willing to debug. You could find out what error OpenAI is returning. As mentioned above you can check the `exception_response` function in `error_handling.py` maybe the original `openai.error.APIConnectionError` is more helpful. 
`

**Comment by kraonn** [comment]
I'm not sure how to debug that APIConnectionError error further, everything I can find suggests that it doesn't give any more specifics about the problem. The image generation script also works perfectly if I invoke it from terminal, but not when run from the Alfred workflow.

**Comment by kraonn** [comment]
I have not, I've only set the API key. 

I rebooted into safe mode just to be sure I didn't have some network filter utility running that would be intercepting the script, but got the same behavior.

Could it be a permissions issue? Do we know what user the Alfred workflow executes under?

**Comment by chrislemke** [comment]
> Could it be a permissions issue? Do we know what user the Alfred workflow executes under?

Nothing I know of. 🤔

One Idea. You could exchange the `make_chat_request` function in the `text_chat.py` with this:

```
def make_chat_request(
    prompt: str,
    temperature: float,
    max_tokens: Optional[int],
    top_p: int,
    frequency_penalty: float,
    presence_penalty: float,
) -> Tuple[str, str]:
    handle_custom_prompts(prompt)
    messages = create_message(prompt)
    try:
        response = (
            openai.ChatCompletion.create(
                model="gpt-3.5-turbo",
                messages=messages,
                temperature=temperature,
                max_tokens=max_tokens,
                top_p=top_p,
                frequency_penalty=frequency_penalty,
                presence_penalty=presence_penalty,
            )
            .choices[0]
            .message["content"]
        )
    except Exception as exception:  # pylint: disable=broad-except
        response = exception._message # Use OpenAI error

    return prompt, response
```

Now it prints the original OpenAI error. Maybe this help us to figure out the problem.

**Comment by kraonn** [comment]
SUCCESS! Seeing the actual error message made it clear that I'd somehow gotten my API key into the configuration field twice, which made it an invalid API key. Deleting my API key from the configuration and re-entering it (once) makes everything work great.

Thanks for your patient help!

**Comment by chrislemke** [comment]
Great! Good to hear. Right now I am working on an error logger. So next time it should be easier to get the proper error message.
