### ISSUE TITLE
Do you have any plan to support DALL-E 3?

### ISSUE THREAD

**Issue by cadesalaberry** [chrislemke/ChatFred#120]
If the title is not enough, do not hesitate to ask for more details!

**Comment by chrislemke** [comment]
Hey @cadesalaberry!
As far as I know currently OpenAI's API only allows access to DALL·E 2:
https://platform.openai.com/docs/models/dall-e

> The current DALL·E model available through our API is the 2nd iteration of DALL·E ...

**Comment by cadesalaberry** [comment]
I did some research to add it myself, but indeed, the [python package](https://github.com/openai/openai-python/blob/284c1799070c723c6a553337134148a7ab088dd8/openai/api_resources/image.py#L9) does not support the new model yet. I'll be waiting from an update then.

Thanks for the reply !

**Comment by Morriz** [comment]
I see that it is possible to target Dall-e 3 with newer versions of the lib, so I propose to reopen this and upgrade asap:

https://platform.openai.com/docs/guides/images/image-generation?context=node
