### ISSUE TITLE
Constant error message: hmm something is wrong with your request, try again later...

### ISSUE THREAD

**Issue by rikkoopman1100** [chrislemke/ChatFred#126]
I had a look at the [troubleshooting section](https://github.com/chrislemke/ChatFred#troubleshooting-%EF%B8%8F)
- [✅] Yes
- [ ] No

**Describe your problem**
Constant error message: hmm something is wrong with your request, try again later... Cannot find what the problem is.

**To Reproduce**
Don't know really, it just doesn't work for me

**Screenshots**
<img width="1245" alt="image" src="https://github.com/chrislemke/ChatFred/assets/150725263/7e8ebc33-c847-49c5-9b83-f862d5ce2437">

**Relevant information from the `ChatFred_Error.log` file**
```
Date/Time: 2023-03-10 16:32:29.819957
model: gpt-3.5-turbo
workflow_version: 1.2.0
error_message: Incorrect API key provided: sk-44******************************************PEG2.   You can find your API key at https://platform.openai.com/account/api-keys.
user_prompt: Why do birds fly?
temperature: 0.0
max_tokens: None
top_p: 1
frequency_penalty: 0.0
presence_penalty: 0.0
```

**Additional context**
Not familiar with log files. Don't know where to find those.

**Comment by chrislemke** [comment]
Hey @rikkoopman1100!
Have you tried to enter `what does that even mean?` once you received the error? You should receive a more detailed response.

**Comment by marekkaczkowski** [comment]
Same here, it says:

```
😬 Sorry, the error message was not really helpful. Here is the original message from OpenAI:

➡️  The model `gpt-4` does not exist or you do not have access to it. Learn more: https://help.openai.com/en/articles/7102672-how-can-i-access-gpt-4.
```

An API key is set correctly (double-checked) and I have a subscription.

**Comment by rikkoopman1100** [comment]
Hi all,

Now I'm getting one step further, thanks for your help! The only thing left
is the limit like it says here when I type something right now.
[image: image.png]

How do I fix this?

Met vriendelijke groet,

*Rik Koopman*
*Mede-eigenaar | Dr. Traffic*
M: +31640767400
E: ***@***.***
A: Gildestraat 1, 1704AG Heerhugowaard


Op wo 15 nov 2023 om 01:26 schreef Marek Kaczkowski <
***@***.***>:

**Comment by chrislemke** [comment]
> Same here, it says:
> 
> ```
> 😬 Sorry, the error message was not really helpful. Here is the original message from OpenAI:
> 
> ➡️  The model `gpt-4` does not exist or you do not have access to it. Learn more: https://help.openai.com/en/articles/7102672-how-can-i-access-gpt-4.
> ```
> 
> An API key is set correctly (double-checked) and I have a subscription.

Hey @marekkaczkowski!
Looks like you don't have access to GPT-4. Have you checked out the website: https://help.openai.com/en/articles/7102672-how-can-i-access-gpt-4?

**Comment by chrislemke** [comment]
Hey, @rikkoopman1100! 
For privacy concerns, I would recommend you remove your private data from your last post.

Concerning your problem. Looks like you have the same issue as @marekkaczkowski. Please read my response to his question 👆

**Comment by rikkoopman1100** [comment]
Hi Chris,

Okay, but I do have chat gpt premium so I should have access? Anyhow, I've
set it back to gpt3.5 but this gave me the error message. It still doesn't
seem to work.

Met vriendelijke groet,

*Rik Koopman*
*Mede-eigenaar | Dr. Traffic*
M: +31640767400
E: ***@***.***
A: Gildestraat 1, 1704AG Heerhugowaard


Op wo 15 nov 2023 om 14:39 schreef Chris Lemke ***@***.***>:

**Comment by chrislemke** [comment]
Hey @rikkoopman1100!
Unfortunately, that is not correct. Having GPT premium does not mean you have access to the API GPT-4. Sorry! May I help you with your other problem?

**Comment by rikkoopman1100** [comment]
Okay, but how do you get access to the GPT4 api? And also, I switched it
back to 3.5 so why does that also not work then?

Met vriendelijke groet,

*Rik Koopman*
*Mede-eigenaar | Dr. Traffic*
M: +31640767400
E: ***@***.***
A: Gildestraat 1, 1704AG Heerhugowaard


Op do 16 nov 2023 om 17:52 schreef Chris Lemke ***@***.***>:

**Comment by chrislemke** [comment]
Referring to the link in the error message: https://help.openai.com/en/articles/7102672-how-can-i-access-gpt-4

> **How do I access the GPT-4 API?**
If you've made a successful payment of $1 or more, you'll be able to access the GPT-4 API (8k). 
>
>**ChatGPT Plus**
ChatGPT Plus subscribers will get GPT-4 access on chat.openai.com with a usage cap. We will dynamically adjust the exact usage cap depending on demand and system performance in practice. GPT-4 currently has a cap of 50 messages every 3 hours.
Please be patient though — we expect massive demand and will scale up and optimize our systems over the coming months.
Note: this will not provide subscribers with access to the API.

Concerning your error with 3.5. Do you receive the same error message?

**Comment by rikkoopman1100** [comment]
Hi Chris,

Yes, I get this message:
[image: image.png]

Do you know why?

Met vriendelijke groet,

*Rik Koopman*
*Mede-eigenaar | Dr. Traffic*
M: +31640767400
E: ***@***.***
A: Gildestraat 1, 1704AG Heerhugowaard


Op vr 17 nov 2023 om 09:02 schreef Chris Lemke ***@***.***>:

**Comment by marekkaczkowski** [comment]
Ok guys I had to ask ChatGPT for this confusing sh**.

Go to https://platform.openai.com/account/billing/overview and buy some credits. As @chrislemke said:

ChatGPT Plus != access to API

**Comment by marekkaczkowski** [comment]
Yeah same here, terminal chatai works, Genie in vscode works and no luck with ChatFred ;(
<img width="754" alt="Screen Shot 2023-12-06 at 20 41 30" src="https://github.com/chrislemke/ChatFred/assets/273831/60cd1614-04ec-4182-8028-6801149eadfd">
