### ISSUE TITLE
Running CFI multiple times will override the image 

### ISSUE THREAD

**Issue by NeighNeighNeigh** [chrislemke/ChatFred#13]
Hi, sometimes I want to re-roll the image generations, so I bust open Alfred, press up and enter to re-issue the last CFI command. Sadly, doing so will pull down a new image on top of the previous one (since they have the same file name). Would it be possible to append a number and keep both files?

**Comment by chrislemke** [comment]
Hey! @NeighNeighNeigh!
Sure, that is actually a very good idea. We could add the timestamp to the filename. So it would be unique every time.

**Comment by chrislemke** [comment]
I just implemented it. The file name will look like this `ChatFred_a_dog_sitting_on_a_bird_2023-03-09_05-51-54.png`.
This improvement will be a part of the next release.

Thanks for the good idea.

**Comment by chrislemke** [comment]
Hey!
I just released a [new version](https://github.com/chrislemke/ChatFred/releases/tag/v1.2.0) with your requested feature.
