### ISSUE TITLE
cf does not work

### ISSUE THREAD

**Issue by draugvar** [chrislemke/ChatFred#14]
Hi,
I have tried this workflow and it seems all to work correctly but the cf command. It always says "something wrong..." as you can see from the picture attached. Did i messed something?

SR
<img width="1290" alt="Screenshot 2023-03-09 at 17 11 08" src="https://user-images.githubusercontent.com/12036000/224084415-a55c68eb-799d-453e-80ac-becb0e2eba3e.png">

**Comment by chrislemke** [comment]
Hey @draugvar!
This error message is just saying that you received an `openai.error.InvalidRequestError`. [Here](https://help.openai.com/en/articles/6897194-invalidrequesterror) you can read more about it. 

In [this message](https://github.com/chrislemke/ChatFred/issues/12#issuecomment-1462366528) I describe how to get the original error message from OpenAI. That could help to debug your problem.

**Comment by draugvar** [comment]
HI here the output when I ask chatFred just "hello":
<img width="1295" alt="Screenshot 2023-03-10 at 09 27 15" src="https://user-images.githubusercontent.com/12036000/224264326-ea220c97-4e95-42de-b86b-7780760ea681.png">

**Comment by chrislemke** [comment]
Hey! 
I just created a new [release (1.2.0)](https://github.com/chrislemke/ChatFred/releases/tag/v1.2.0). It contains some new features for [troubleshooting](https://github.com/chrislemke/ChatFred#troubleshooting-%EF%B8%8F) maybe this can help you solve your issue.

**Comment by draugvar** [comment]
Hi,
Here attached a screenshot using the last version and the error log:

`Date/Time: 2023-03-13 09:23:50.802024
model: gpt-3.5-turbo
workflow_version: 1.2.1
error_message: This model's maximum context length is 4097 tokens. However, your messages resulted in 4263 tokens. Please reduce the length of the messages.
user_prompt: what's your name
temperature: 0.0
max_tokens: None
top_p: 1
frequency_penalty: 0.0
presence_penalty: 0.0`

As you can see i just asked what's your name and it says maximum context length.
<img width="1229" alt="Screenshot 2023-03-13 at 09 23 18" src="https://user-images.githubusercontent.com/12036000/224647354-bfc5dcdf-5dd0-4310-9035-83be07d0ee7e.png">

**Comment by chrislemke** [comment]
Hey!
That is indeed very strange behavior. Here are some things you may try:
- Set the `Maximum tokens` in the workflow's configuration to something like 1000
- Remove the Worfklow and all files in the workflows data directory: `~/Library/Application Support/Alfred/Workflow Data/something with ChatFred/` and install it again.

Hope this helps. Good luck 🤞

**Comment by draugvar** [comment]
reinstalling it was the solution, thanks.

**Comment by chrislemke** [comment]
Great! Enjoy playing with it.
