### ISSUE TITLE
How to add proxy for the API call to openai

### ISSUE THREAD

**Issue by mizeng** [chrislemke/ChatFred#16]
Great tool! However my default network has problem with connecting to openai.

I tried to add proxy to your script. In "openai/_init.py_", I add below code
```
#proxy = None
proxy = {
   'http': 'xxx:80',
   'https': 'xxx:80',
}
```
But seems still not working. Am I missing something? How can I debug it more efficient? 
Need your insights, thanks a lot

**Comment by chrislemke** [comment]
Hey @mizeng!
Good question. Not really sure how it works. You could try something like this:
```
import openai

openai.api_key = os.getenv("api_key")
openai.proxy = # your proxy
```
In the `text_chat.py` file. But it should actually do what you were trying in the `__init__.py` file. Unfortunately, OpenAI's [documentation](https://platform.openai.com/docs/api-reference/introduction) is pretty bad. 

Sorry that I could not help you more.

**Comment by mizeng** [comment]
weird. below code snippet works for me.
```
import requests

url = "https://api.openai.com/v1/completions"

payload = "{\n  \"model\": \"text-davinci-003\",\n  \"prompt\": \"Say this is a test\",\n  \"max_tokens\": 7,\n  \"temperature\": 0\n}"
headers = {
    'authorization': "Bearer xxxx",
    'content-type': "application/json"
    }
proxy = {
   'http': 'sjd-entbc-001.corp.ebay.com:80',
   'https': 'sjd-entbc-001.corp.ebay.com:80',
}

s = requests.Session()
s.proxies = proxy
response = s.request("POST", url, data=payload, headers=headers)

print(response.text)
```

**Comment by chrislemke** [comment]
Strange. What error message you are getting if you use OpenAI's Python API?

**Comment by mizeng** [comment]
goes to this exception , `'Error communicating with OpenAI: Proxy URL had no scheme, should start with http:// or https://'`. 
I tried add "http://" to the proxy value, but no use.
```
 except requests.exceptions.RequestException as e:
            raise error.APIConnectionError(
                "Error communicating with OpenAI: {}".format(e)
            ) from e
```

**Comment by mizeng** [comment]
Found the issue, my fault. I didn't notice I set https_proxy in the workflow settings.

**Comment by chrislemke** [comment]
Cool, thanks for letting me know. Enjoy ChatFred!

**Comment by mizeng** [comment]
So in short, if you want to use proxy in this workflow.
open file `/src/libs/openai/__init__.py` , and add below code to specify the proxy
```
#proxy = None
proxy = {
   'http': 'xxx:80',
   'https': 'xxx:80',
}
```

**Comment by chrislemke** [comment]
Thanks for investigating in this. Feel free to create a pull request implementing this.
