### ISSUE TITLE
nothing happens 

### ISSUE THREAD

**Issue by lazallen** [chrislemke/ChatFred#17]
Hi, thinks for writng this plugin, i'm having the following issues :) 

I had a look at the [troubleshooting section](https://github.com/chrislemke/ChatFred#troubleshooting-%EF%B8%8F)
- [/ ] Yes
- [ ] No

**Describe the bug**
I've installed CF, but nothing happens when I type a command starting with "cf", no error is displayed.  Also my API key does no get triggered, it says "never used" in the openai console still so I expect that CF isn't even getting as far as calling it.  Additionally the ~/Library/Application Support/Alfred/Workflow Data/ folder is empty so no log file to look at. I've tried restoring defaul settings and generating another API key but get the same result

**To Reproduce**
1. open Alfred2. 
2. type "cf <request>"
3. hit enter
4.experience nothing happening 

**Expected behavior**
cf responds in large type with chatgtp's response

**Screenshots**

**Relevant information from the `ChatFred_Error.log` file**
```
Date/Time: 2023-03-10 16:32:29.819957
model: gpt-3.5-turbo
workflow_version: 1.2.0
error_message: none
user_prompt: <any>
<<all other settings as defaults>>
temperature: 0.0
max_tokens: None
top_p: 1
frequency_penalty: 0.0
presence_penalty: 0.0
```

**Additional context**

**Comment by chrislemke** [comment]
Hey @lazallen!

There was a bug in the code. Please try the new [version 1.2.1](https://github.com/chrislemke/ChatFred/releases/tag/v1.2.1).

**Comment by chrisnkrueger** [comment]
@chrislemke The last version works for me 🎉

**Comment by chrislemke** [comment]
Good to know. Thanks for your feedback. Hope it also works for the other guys!

**Comment by lazallen** [comment]
its stil not working for me, same as above, got this from the debug console 

[21:04:43.462] ERROR: ChatFred[Run Script] xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun

**Comment by chrislemke** [comment]
Looks like there is something fishy with the Command line tools. You could try installing them (again): `xcode-select --install`.

**Comment by CullumAttwell** [comment]
Same issue for me. I have tried reinstalling but the same issue persists.

**Comment by akuzubasli** [comment]
Same problem here after re-installing `xcode-select --install`. Nothing happens when typing`cf`.

**Comment by chrislemke** [comment]
That is really strange. I will investigate more into this. Any additional information you guys can share? It is pretty hard to debug since it works for me.

E.g.: what python version is installed: `python --version`
