### ISSUE TITLE
do you need premium chat-gpt to use this workflow?

### ISSUE THREAD

**Issue by benkhademi** [chrislemke/ChatFred#19]
I had a look at the [troubleshooting section](https://github.com/chrislemke/ChatFred#troubleshooting-%EF%B8%8F)
- [ x] Yes
- [ ] No

**Describe the bug**
Do you need premium version of chatgpt?

**To Reproduce**

**Expected behavior**

**Screenshots**

**Relevant information from the `ChatFred_Error.log` file**
```
Date/Time: 2023-03-10 16:32:29.819957
model: gpt-3.5-turbo
workflow_version: 1.2.0
error_message: Incorrect API key provided: sk-44******************************************PEG2.   You can find your API key at https://platform.openai.com/account/api-keys.
user_prompt: Why do birds fly?
temperature: 0.0
max_tokens: None
top_p: 1
frequency_penalty: 0.0
presence_penalty: 0.0
```

**Additional context**

**Comment by chrislemke** [comment]
Hi @benkhademi!
Thanks for reaching out. What do you mean by "**premium chat-gpt**". To run this workflow you need an OpenAI account to create an API key. That's about it.
