### ISSUE TITLE
Problems with Korean prompts

### ISSUE THREAD

**Issue by circumeo** [chrislemke/ChatFred#21]
Chatfred gives a very good answer when you ask a question in English, but it doesn't work normally if you ask a question in Korean.

This is a problem that occurred with both the "cf" and "cft" commands.

On the chatgpt site, if you ask a question in Korean, the normal answer will be output, so I wonder if you can solve this problem by changing the settings in the workflow!

**Comment by chrislemke** [comment]
Hey @circumeo!
Hm 🤔, that is actually an interesting problem. Do you enter the prompt in Hangul or in the Latin alphabet?

**Comment by chrislemke** [comment]
Could you provide an example prompt so I can test it?

**Comment by circumeo** [comment]
> Could you provide an example prompt so I can test it?

Should I upload a screenshot or should I write down the sentence I asked?

**Comment by chrislemke** [comment]
I would prefer a sentence. So I can copy it.

**Comment by circumeo** [comment]
"비빔밥 레시피를 알려줘"
Thank you for the test! 😊

**Comment by chrislemke** [comment]
It seems to be connected that ChatGPT always receives some parts of the prior conversation. In the workflow's configuration, there is the *ChatGPT history length* for adjusting this. You could decrease this number so the model only receives the n-newest requests. Alternatively, you could also use the `forget me` prompt which removes all the conversations from the cache.

<img width="897" alt="Screenshot 2023-03-13 at 12 02 47" src="https://user-images.githubusercontent.com/11752694/224684500-a4dd8d44-524b-47d1-8012-5c8195195f2f.png">

I will think of a way to improve this and may provide an update in the future. But for now, this seems to be the solution.

**Comment by circumeo** [comment]
> It seems to be connected that ChatGPT always receives some parts of the prior conversation. In the workflow's configuration, there is the _ChatGPT history length_ for adjusting this. You could decrease this number so the model only receives the n-newest requests. Alternatively, you could also use the `forget me` prompt which removes all the conversations from the cache. I will think of a way to improve this and may provide an update in the future. But for now, this seems to be the solution.
> 
> <img alt="Screenshot 2023-03-13 at 12 02 47" width="897" src="https://user-images.githubusercontent.com/11752694/224684500-a4dd8d44-524b-47d1-8012-5c8195195f2f.png">

Thank you so much for explaining in detail! 😊
It helped me a lot to solve the problem :)
