### ISSUE TITLE
Multiline result

### ISSUE THREAD

**Issue by dna75** [chrislemke/ChatFred#26]
Is it possible to get a multiline answer within Alfred?
The Large font type or the answer in a text file is ok but it would be great to show the answer within Alfred.
This makes reviewing the answer much easier.

**Comment by chrislemke** [comment]
Hey @dna75!
I thought about this right at the beginning of the project. It would be possible but Alfred is not made for showing one text in multiple lines. It would be kind of a hack and the icon would repeat on every line. It may also be complicated if the response is really long. But I'll keep it in mind.
