### ISSUE TITLE
Missing module

### ISSUE THREAD

**Issue by ChristianCoenen** [chrislemke/ChatFred#3]
Hey 👋 Nice idea with the Alfred integration!

I installed the latest version and noticed the following output in Alfred debugging when trying to use ChatFred:
```shell
ModuleNotFoundError: No module named 'typing_extensions'
```
=> it's currently not working for me.

**Comment by chrislemke** [comment]
Hey @ChristianCoenen!
Thanks for pointing it out. Will investigate it right away!

**Comment by ChristianCoenen** [comment]
Thanks for looking into this. I can confirm that it works on the current `dev` version.

**Comment by chrislemke** [comment]
Thanks for helps for helping! 🙏

Created a [new release](https://github.com/chrislemke/ChatFred/releases/tag/v1.0.2).
