### ISSUE TITLE
Show result on empty history

### ISSUE THREAD

**Issue by vitorgalvao** [chrislemke/ChatFred#35]
Right now, on the first run of the `cf` Script Filter, the following happens:

1. Type `cf` and see results in Alfred.
2. Type space to start the prompt. Results in Alfred disappear.
3. Type first letter. Result reappears.

Step two makes is seem something went wrong, but it’s just the script returning zero results because there is no history yet. Maybe it’s worth it to output “No prompt history yet” as a subtitle or something in that case?

**Comment by chrislemke** [comment]
Improved in: [v1.3.1](https://github.com/chrislemke/ChatFred/releases/tag/v1.3.1)
