### ISSUE TITLE
Non descriptive universal actions

### ISSUE THREAD

**Issue by xilopaint** [chrislemke/ChatFred#38]
Is your intention to have the last three universal actions? There's no description for them.

<img width="764" alt="Screenshot 2023-03-25 at 16 03 39" src="https://user-images.githubusercontent.com/11052366/227736497-3c9a092b-e379-4be3-b29a-c02d0199417f.png">

**Comment by chrislemke** [comment]
Hey @xilopaint!

I tried to reproduce it but I always get only one result. Could you define a few steps on how to reproduce it? Or is it just the usual way?

**Comment by xilopaint** [comment]
I just need to select some text and invoke Alfred via the hotkey for universal actions.

**Comment by chrislemke** [comment]
I could reproduce it. It will be fixed in the next version. Thanks for pointing it out! 🙏

**Comment by chrislemke** [comment]
Fixed in: [1.3.2](https://github.com/chrislemke/ChatFred/releases/tag/v1.3.2)
