### ISSUE TITLE
Unable to use work flow

### ISSUE THREAD

**Issue by dt437** [chrislemke/ChatFred#40]
I had a look at the [troubleshooting section](https://github.com/chrislemke/ChatFred#troubleshooting-%EF%B8%8F)
- [ ] Yes
- [ ] No

**Describe your problem**

**To Reproduce**

**Screenshots**

**Relevant information from the `ChatFred_Error.log` file**
![CleanShot 2023-03-26 at 12 15 25](https://user-images.githubusercontent.com/128991877/227789468-b3c108ca-be90-4f89-9b58-a6f2bff07bde.gif)

```
Date/Time: 2023-03-10 16:32:29.819957
model: gpt-3.5-turbo
workflow_version: 1.2.0
error_message: Incorrect API key provided: sk-44******************************************PEG2.   You can find your API key at https://platform.openai.com/account/api-keys.
user_prompt: Why do birds fly?
temperature: 0.0
max_tokens: None
top_p: 1
frequency_penalty: 0.0
presence_penalty: 0.0
```

**Additional context**

**Comment by chrislemke** [comment]
Hey! 
It says your API-key is wrong:
> sk-44******************************************PEG2.   You can find your API key at https://platform.openai.com/account/api-keys.

Have you checked if you enter the correct key? Have you checked if Python is installed?

**Comment by chrislemke** [comment]
Hey @dt437!

Do you still have problems or can I close this issue?
