### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by harrisongoeldner** [chrislemke/ChatFred#41]
I had a look at the [troubleshooting section](https://github.com/chrislemke/ChatFred#troubleshooting-%EF%B8%8F)
- [X] Yes
- [ ] No

**Describe the bug**
When I type `cf` only two options show up and debug shows that ChatFred is erroring. 

**To Reproduce**
1. Type `cf` in Alfred prompt

**Expected behavior**
I expected to be able to search ChatGPT.

**Screenshots**
<img width="586" alt="image" src="https://user-images.githubusercontent.com/74375558/227867998-d3c9928b-62a2-4870-a5bd-6da071a8adfc.png">
<img width="586" alt="image" src="https://user-images.githubusercontent.com/74375558/227868093-3b02bc32-08eb-4434-81af-0c13f45e8818.png">

**Alfred's debug log**
```
 VARIABLES:{
  always_copy_to_clipboard = "1"
  always_speak = "0"
  api_key = "sk-************************************************" # Removed for privacy
  cf_aliases = "joke=tell me a joke;"
  chat_gpt_model = "gpt-3.5-turbo"
  frequency_penalty = "0.0"
  history_length = "3"
  history_type = "search"
  image_size = "512"
  instruct_gpt_model = "text-davinci-003"
  jailbreak_prompt = ""
  max_tokens = ""
  presence_penalty = "0.0"
  save_to_file = "0"
  save_to_file_dir = "/Users/***" # Removed for privacy
  show_loading_indicator = "1"
  show_notifications = "1"
  temperature = "0"
  top_p = "1"
  transformation_prompt = "Write the text so that each letter is replaced by its successor in the alphabet."
  user_prompt = ""
}
RESPONSE:

ERROR: ChatFred[Script Filter] Code 1: Traceback (most recent call last):
  File "/Users/ha****************/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.7C443488-F6BE-4801-8427-5835156D12BB/src/history_manager.py", line 77, in <module>
    provide_history()
  File "/Users/ha*****************/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.7C443488-F6BE-4801-8427-5835156D12BB/src/history_manager.py", line 42, in provide_history
    if row[3] == "0":
       ~~~^^^
IndexError: list index out of range
```

**Comment by chrislemke** [comment]
Hi @harrisongoeldner!
Thanks for reporting this issue. Could you check if [removing the `ChatFred_ChatGPT.csv`](https://github.com/chrislemke/ChatFred#chatfred_chatgptcsv-) helps?

**Comment by neo-anderson** [comment]
I had this same issue. I had to change `if row[3] == 0` to `if len(row) > 3 and row[3] == 0` to make it work. I do not see that csv file in the workflow folder
