### ISSUE TITLE
How to delete the Q&A record in the hotkey "cf"？

### ISSUE THREAD

**Issue by xushichen** [chrislemke/ChatFred#43]
I had a look at the [troubleshooting section](https://github.com/chrislemke/ChatFred#troubleshooting-%EF%B8%8F)
- [ ] Yes
- [ ] No

**Describe your problem**

**To Reproduce**

**Screenshots**

**Relevant information from the `ChatFred_Error.log` file**
```
Date/Time: 2023-03-10 16:32:29.819957
model: gpt-3.5-turbo
workflow_version: 1.2.0
error_message: Incorrect API key provided: sk-44******************************************PEG2.   You can find your API key at https://platform.openai.com/account/api-keys.
user_prompt: Why do birds fly?
temperature: 0.0
max_tokens: None
top_p: 1
frequency_penalty: 0.0
presence_penalty: 0.0
```

**Additional context**

**Comment by chrislemke** [comment]
Please read the [troubleshooting section](https://github.com/chrislemke/ChatFred#troubleshooting-%EF%B8%8F) first.

**Comment by xushichen** [comment]
Delete all can use 'forget me', how delete one of them？

**Comment by chrislemke** [comment]
That is not possible. Sorry.

**Comment by chrislemke** [comment]
I guess this is solved. I will close it.
