### ISSUE TITLE
Support for Alfred 4?

### ISSUE THREAD

**Issue by yichechang** [chrislemke/ChatFred#46]
**Is your feature request related to a problem? Please describe.**
Alfred 4 complains that this workflow requires Alread 5 and above because it uses the "Workflow User Configuration". 

**Describe the solution you'd like**
Is there a way that this workflow can be used with Alfred 4, even if it means some features/configurations will not be available?

Thank you for considering!

**Comment by chrislemke** [comment]
Hey!
There is no plan to support Alfred 4 since the "Workflow User Configuration" is a crucial part of the workflow. Sorry!

**Comment by yichechang** [comment]
Thanks for the answer! Maybe this will be the trigger for me to finally upgrade to Alfred 5 🤣
