### ISSUE TITLE
Temperature should be a float

### ISSUE THREAD

**Issue by StonkGodCapital** [chrislemke/ChatFred#5]
Currently only allows 0 or 1, in a proper setup it's usually around 0.6-0.75.

`__temperature = int(os.getenv("temperature") or 0)`

should be

`__temperature = float(os.getenv("temperature") or 0)`

Awesome work, thank you!

**Comment by chrislemke** [comment]
Hey @StonkGodCapital!

Thanks for pointing this out 🙏. I fixed the issue and created a new [release](https://github.com/chrislemke/ChatFred/releases/tag/v1.0.3).
