### ISSUE TITLE
Supports custom API address

### ISSUE THREAD

**Issue by llity** [chrislemke/ChatFred#51]
Hi,

Please support custom API address, we can use API Key and domain api.chatai.xxx to use ChatAI.

Thanks

**Comment by chrislemke** [comment]
Hey!
Not sure what you mean. Could you provide a documentation for ChatAi?

Thanks.

**Comment by llity** [comment]
I used a third-party chat AI service that supports custom API addresses for OpenAI debugging clients, but there is inadequate documentation available.

![image](https://user-images.githubusercontent.com/11771112/231759269-a1459677-d2ad-4c03-bdad-1fa0c5f32fb5.png)

**Comment by chrislemke** [comment]
This feature is now available in [`develop`](https://github.com/chrislemke/ChatFred/tree/develop) and will be released soon. Thanks @JettChenT!

**Comment by llity** [comment]
Great! The functionality of chatFred is constantly improving.

**Comment by chrislemke** [comment]
https://github.com/chrislemke/ChatFred/releases/tag/v1.5.0
