### ISSUE TITLE
Paste response to frontmost app is fail.

### ISSUE THREAD

**Issue by iT-Boyer** [chrislemke/ChatFred#54]
I had a look at the [troubleshooting section](https://github.com/chrislemke/ChatFred#troubleshooting-%EF%B8%8F)
- [ x ] Yes
- [ ] No

**Describe the bug**

```
Paste response to frontmost app: If enabled, the response will be pasted to the frontmost app. If this feature is switched on, the response will not be shown in Large Type. Alternatively you can also use the option ⌘ ⌥ when sending the request to ChatGPT. Default: off.

```
`Paste response to frontmost app` is enabled, When ⌘ ⌥ dnot past to the frontmost app , but be shown in Large Type.

**Comment by chrislemke** [comment]
Sorry, I can not reproduce this bug. For me it works perfectly. You need to provide more information so I can investigate more into this.

**Comment by chrislemke** [comment]
Hey @iT-Boyer!
Is your problem fixed? Can I close this issue?
