### ISSUE TITLE
Error in running chatfred

### ISSUE THREAD

**Issue by fouadzreik** [chrislemke/ChatFred#56]
I had a look at the [troubleshooting section](https://github.com/chrislemke/ChatFred#troubleshooting-%EF%B8%8F)
- [x] Yes
- [ ] No

**Describe your problem**

Installed workflow. It does not run. The debug window shows this error:

ERROR: ChatFred[Run Script] xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun

When I check ChatGPT API. It is not getting any requests.

**To Reproduce**

**Screenshots**

**Relevant information from the `ChatFred_Error.log` file**
```
Date/Time: 2023-03-10 16:32:29.819957
model: gpt-3.5-turbo
workflow_version: 1.2.0
error_message: Incorrect API key provided: sk-44******************************************PEG2.   You can find your API key at https://platform.openai.com/account/api-keys.
user_prompt: Why do birds fly?
temperature: 0.0
max_tokens: None
top_p: 1
frequency_penalty: 0.0
presence_penalty: 0.0
```

**Additional context**

**Comment by chrislemke** [comment]
Hey @fouadzreik!
The first idea which comes to my mind is that you may need to install Xcode developer tools. Try this - just type it in your terminal: `xcode-select --install`.
