### ISSUE TITLE
Customize the "Stay tuned" message

### ISSUE THREAD

**Issue by Stooovie** [chrislemke/ChatFred#59]
**Is your feature request related to a problem? Please describe.**
I find the "Stay tuned" wording annoying through repetition, but the indicator is valuable. Please provide a way to customize this message. I'd use just simple "thinking..." or even just "..."

**Additional context**
I'd do it myself but as a non-developer, I haven't found the string that I could customize.

**Comment by chrislemke** [comment]
Here you go: https://github.com/chrislemke/ChatFred/releases/tag/v1.5.1

**Comment by chrislemke** [comment]
:-) You can adjust the size in the workflow. Just click on the item marks with the arrow. At the top, you can make some changes. I guess when you adjust the font size the box will decrease in size. Unfortunately, those settings can not be made in the Workflow's configuration.

<img width="1151" alt="Screenshot 2023-04-25 at 15 21 16" src="https://user-images.githubusercontent.com/11752694/234291161-434b422d-8740-4f5d-9349-cb0a55a5a4d5.png">

<img width="977" alt="Screenshot 2023-04-25 at 15 23 29" src="https://user-images.githubusercontent.com/11752694/234290804-1f7565c3-53d5-4b80-9505-64e9d5eeedcd.png">

**Comment by Stooovie** [comment]
perfect! thank you so much!
