### ISSUE TITLE
You exceeded your current quota

### ISSUE THREAD

**Issue by arroyorodrigo** [chrislemke/ChatFred#62]
I had a look at the [troubleshooting section](https://github.com/chrislemke/ChatFred#troubleshooting-%EF%B8%8F)
- [x ] Yes
- [ ] No

**Describe your problem**
It always delivers the following message to me "🚨 You have reached the rate limit. Check your settings in your OpenAI dashboard."

**Screenshots**
[my api usage.](https://i.imgur.com/92Nveyi.png)

**Relevant information from the `ChatFred_Error.log` file**
```
---
Date/Time: 2023-05-12 10:54:47.606311
model: gpt-3.5-turbo
workflow_version: 1.5.1
error_message: You exceeded your current quota, please check your plan and billing details.
user_prompt: traduce esta sentencia al inglés
temperature: 0.0
max_tokens: None
top_p: 1
frequency_penalty: 0.0
presence_penalty: 0.0
```

thanks!

**Comment by chrislemke** [comment]
Hey @arroyorodrigo!
Whenever you get such an error message you can answer with e.g. `wtf` to receive the original OpenAI error message. It seems to be what it says:  

> You exceeded your current quota, please check your plan and billing details.

Here is a link with some additional information:
https://help.openai.com/en/articles/6891831-error-code-429-you-exceeded-your-current-quota-please-check-your-plan-and-billing-details

Hope this helped. Please reach out if you need further assistance.
