### ISSUE TITLE
Support for prompt chaining?

### ISSUE THREAD

**Issue by merchako** [chrislemke/ChatFred#66]
Does this workflow support prompt chaining? 

- If not, I would love to have it as a feature.
- If so, could you mention it in the README with an example?

By "prompt chaining" I mean that if I submit multiple queries, the LLM uses the previous queries as context for the latter queries. They belong in a thread together. If you support this by default, how would a user start a fresh context?

Clarity on support for prompt chaining would help me (and other potential users) make a decision whether to use this workflow versus similar alternative.

**Comment by merchako** [comment]
I looks like prompt chaining is supported by default. To start a fresh context, the README describes the `forget me` command—which I didn't notice in my first read. The number of prompts included in the context is limited by the "ChatGPT history length" preference within the workflow.
![Screenshot 2023-06-02 at 10 44 04 AM](https://github.com/chrislemke/ChatFred/assets/441789/dc31b000-e7d5-4e88-98f7-fc7b188aec17)

My problem is solved. Devs, you can ignore this thread, or take it as a signal to perhaps rephrase or somehow make it easier to spot a feature like this.

**Comment by chrislemke** [comment]
Hey @merchako!
Thanks for your feedback. You have a valid point. I will improve the readme a bit. Thanks!
