### ISSUE TITLE
how to chat to the previous gpt reply?

### ISSUE THREAD

**Issue by crazyxhz** [chrislemke/ChatFred#68]
I had a look at the [troubleshooting section](https://github.com/chrislemke/ChatFred#troubleshooting-%EF%B8%8F)
- [x] Yes
- [ ] No

**Describe your problem**

how to chat to the previous gpt reply? Or this is a one time conversation?

**Comment by chrislemke** [comment]
Hey @crazyxhz!
Not sure if I understand your question correctly. Is [this](https://github.com/chrislemke/ChatFred/issues/66) maybe your issue?
