### ISSUE TITLE
Token overuse

### ISSUE THREAD

**Issue by YYL246** [chrislemke/ChatFred#71]
I had a look at the [troubleshooting section](https://github.com/chrislemke/ChatFred#troubleshooting-%EF%B8%8F)
- [x] Yes
- [ ] No

**Describe your problem**
Hi! 

Thank you for the workflow! It is working nicely, but sometimes even a simple input takes a huge amount of tokens. Is there any way to minimize the tokens used?

**To Reproduce**
Steps to reproduce the behaviour:
1. Type "cf" in Alfred followed by the following prompt: Generate a single image prompt describing what I see on a travelling trip in the countryside. Please don't include any famous tourist spots. I see a flower. Hit "Enter". 
2. ChatFred returns an answer <100 words. 
3. Go to my OpenAI account to check usage. Each time they exceed 1000 tokens. 
<img width="779" alt="image" src="https://github.com/chrislemke/ChatFred/assets/64901536/37bdbffc-8d13-4810-85a9-e367025f36ba">

**Screenshots**
My configurations:
<img width="501" alt="image" src="https://github.com/chrislemke/ChatFred/assets/64901536/d12b4066-8643-4dfc-a51f-6ecf96f9394a">

**Relevant information from the `ChatFred_Error.log` file**
No error displayed, so no error log. 

Thank you!

**Comment by chrislemke** [comment]
Hey @YYL246!
This is definitely strange behavior. Unfortunately, I can not reproduce it. For the the number count is as expected.

<img width="344" alt="Screenshot 2023-06-24 at 11 55 40" src="https://github.com/chrislemke/ChatFred/assets/11752694/78a8f65a-be51-4a8c-8f36-4fbeda2b1ad9">

**Comment by YYL246** [comment]
@chrislemke Hi Chris,

I reinstalled the workflow, usage has gone down now but still higher than expected:
<img width="753" alt="image" src="https://github.com/chrislemke/ChatFred/assets/64901536/17fc43c6-68f5-41d2-90ee-3fa3565e944a">

Happy to try other solutions and thanks for looking into this :)

**Comment by chrislemke** [comment]
@YYL246! 
Thanks for the update! Still very strange. I will investigate more and keep you in the loop.
