### ISSUE TITLE
Cannot Set the history_length to 0 Despite Being Provided

### ISSUE THREAD

**Issue by Sponge-bink** [chrislemke/ChatFred#78]
I had a look at the [troubleshooting section](https://github.com/chrislemke/ChatFred#troubleshooting-%EF%B8%8F)
- [x] Yes
- [ ] No

**Describe the bug**
Cannot set the `history_length` to 0 despite provided.

**To Reproduce**
1. Configure Workflow…
2. Set `history_length` to 0 and save
3. Talk to ChatGPT
4. See error and found `error_message: This model's maximum context length is 4097 tokens. However, your messages resulted in 26794 tokens. Please reduce the length of the messages.` in log.

**Expected behavior**
Talk to ChatGPT with `history_length` set to 0. 

The problem seems to be caused by this logic in workflow/src/text_chat.py

```python
    return history[-__history_length:]
``` 

Cuz it will just return the full history if __history_length is 0.

Suggested and tested fix:

```python
    return history[len(history) - __history_length:]
``` 

**Relevant information from the `ChatFred_Error.log` file**
```
Date/Time: 2023-07-31 05:53:06.224087
model: gpt-3.5-turbo
workflow_version: 1.5.1
error_message: This model's maximum context length is 4097 tokens. However, your messages resulted in 26794 tokens. Please reduce the length of the messages.
user_prompt: ?
temperature: 0.0
max_tokens: None
top_p: 1
frequency_penalty: 0.0
presence_penalty: 0.0
```

**Additional context**

**Comment by toolman11** [comment]
Yes, please fix this... additionally, if I set it to a low number such as 1 or 2, it doesn't mind the setting. It just shows everything. IOW, it doesn't work :(

**Comment by chrislemke** [comment]
Thanks for reporting this bug. Unfortunately, I am quite busy recently. Maybe someone wants to create a PR?

**Comment by Sponge-bink** [comment]
I created a PR #80 ;)

**Comment by chrislemke** [comment]
Hey @Sponge-bink! 
Thanks for your PR. I already created a new release: https://github.com/chrislemke/ChatFred/releases/tag/v1.5.2

@toolman11 Could you check if this fix is also solving your issue? Thanks!

**Comment by toolman11** [comment]
No change for me. I deleted the workflow, downloaded ChatFred-1.5.3.alfredworkflow and installed it, added API key, set the "ChatGPT history length" to 1, then 3, then 0, and the complete history is still there (no changes to the history list I see when I invoke Alfred and type "cf ". I'm using the latest (August 2nd, I believe) version of Alfred 5.

**Comment by Sponge-bink** [comment]
That's not what that option means, it just control how many recent messages got to actually send to ChatGPT (to provide better context / cut down token usage). You will see many history messages from Alfred before you send the query, it's there so that you can reuse a prompt (hit Tab key) or just view the result again (hit Return). 

What you are experiencing is an expected behavior.

**Comment by toolman11** [comment]
Understood... especially now that I read the sub-text :) Sorry for the mis-understanding.
