### ISSUE TITLE
Support for gpt-3.5-turbo

### ISSUE THREAD

**Issue by ShravanSunder** [chrislemke/ChatFred#9]
The new model is 10x cheaper than davinci.  Would you be able to support it?

**Comment by chrislemke** [comment]
Hey @ShravanSunder!
At the moment the support for ChatGPT is in beta. You can download it [here](https://github.com/chrislemke/ChatFred/releases/tag/v1.1.0-dev2).

Check out the [readme](https://github.com/chrislemke/ChatFred#talk-to-chatgpt--in-beta-download-it-here) for more information.

Enjoy!
